#!/bin/bash

# This script can be ran from your `crontab -e` to continually run
#
# Use an entry similar to the below
#
#  *  *  *   *   *      cd $HOME/path/to/weekly-random-reminder/ && ./cron
#

export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
if command -v pyenv 1>/dev/null 2>&1; then
  eval "$(pyenv init -)"
  eval "$(pyenv virtualenv-init -)"
fi

pyenv local 3.7.3

/usr/bin/nice -n 10 $HOME/.poetry/bin/poetry run python reminder.py
